#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }
usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

# DPA_ARGS="${DPA_ARGS:-}"; unset by default

if [ -n "${DPA_ARGS}" ] \
&& [ -n "${DPA_AS_S6SVC}" ];
then
    # additional args added for DPA_CONF and certificate
    if [ -f "${DPA_CONF}" ]; then DPA_ARGS="-f ${DPA_CONF} ${DPA_ARGS}"; fi;
    if [ -f "${HAPROXY_CRTFILE}" ]; then DPA_ARGS="${DPA_ARGS} --tls-certificate ${HAPROXY_CRTFILE}"; fi;

    vecho "Starting DataPlaneAPI service.";
    usercmd \
    exec \
    dataplaneapi \
        ${DPA_ARGS} \
    ;
else
    vecho "Skip starting DataPlaneAPI service.";
    sleep infinity;
fi;

