#!/usr/bin/with-contenv bash
set -e

# replace this file with custom postinstall script on child images

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

vecho "Nothing to customize for HAProxy.";
