# syntax=docker/dockerfile:1
#
ARG IMAGEBASE=frommakefile
#
FROM ${IMAGEBASE}
#
# no DataPlaneAPI binary for riscv64, fallback to apk package
#
RUN set -xe \
    && apk add --no-cache --purge -uU \
        ca-certificates \
        haproxy \
        haproxy-dataplaneapi \
        libcap \
        openssl \
        socat \
        tzdata \
    && mkdir -p /defaults \
    && mv /etc/haproxy/haproxy.cfg /defaults/haproxy.cfg.default \
    && mv /etc/haproxy/dataplaneapi.yml /defaults/dataplaneapi.yml.default \
    && setcap 'CAP_NET_BIND_SERVICE=+ep' $(which haproxy) \
#
    && apk del --purge \
        libcap \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /etc/haproxy/ /var/lib/haproxy/
#
EXPOSE 80/tcp 443/tcp 8080/tcp 8080/tcp 8405/tcp
#
HEALTHCHECK \
    --interval=2m \
    --retries=5 \
    --start-period=5m \
    --timeout=10s \
    CMD \
    wget --quiet --tries=1 --no-check-certificate --spider ${HEALTHCHECK_URL:-"http://localhost:80/"} \
    || exit 1
    # && nc -z -i 1 -w 1 localhost 8080 \
    #
#
ENTRYPOINT ["/init"]
